// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAC7jJgqS_zpORBYQ9t50CsbHq22oUktJQ',
    appId: '1:845980933099:web:bec57a25401d50d56a17ae',
    messagingSenderId: '845980933099',
    projectId: 'furiniture-49d70',
    authDomain: 'furiniture-49d70.firebaseapp.com',
    databaseURL: 'https://furiniture-49d70-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'furiniture-49d70.appspot.com',
    measurementId: 'G-7TZ866X04D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDonz0cvDM2dc0uYgOtTCtTXxAClW-vrCo',
    appId: '1:845980933099:android:24d019112f0ae9346a17ae',
    messagingSenderId: '845980933099',
    projectId: 'furiniture-49d70',
    databaseURL: 'https://furiniture-49d70-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'furiniture-49d70.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhdSPqlJIr_lPj7pmA1moXzqVk0IvvLxM',
    appId: '1:845980933099:ios:fc2385ecdad8cf7b6a17ae',
    messagingSenderId: '845980933099',
    projectId: 'furiniture-49d70',
    databaseURL: 'https://furiniture-49d70-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'furiniture-49d70.appspot.com',
    iosBundleId: 'com.example.furiniture',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAhdSPqlJIr_lPj7pmA1moXzqVk0IvvLxM',
    appId: '1:845980933099:ios:fc2385ecdad8cf7b6a17ae',
    messagingSenderId: '845980933099',
    projectId: 'furiniture-49d70',
    databaseURL: 'https://furiniture-49d70-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'furiniture-49d70.appspot.com',
    iosBundleId: 'com.example.furiniture',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAC7jJgqS_zpORBYQ9t50CsbHq22oUktJQ',
    appId: '1:845980933099:web:ac5b830b63608b5b6a17ae',
    messagingSenderId: '845980933099',
    projectId: 'furiniture-49d70',
    authDomain: 'furiniture-49d70.firebaseapp.com',
    databaseURL: 'https://furiniture-49d70-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'furiniture-49d70.appspot.com',
    measurementId: 'G-0GXLR79L0M',
  );
}
